"""Add initial data to Especialidad

Revision ID: 06f9eddb32e9
Revises: e8159734f6b6
Create Date: 2025-03-04 22:26:50.214711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy import String, Integer, Boolean

# revision identifiers, used by Alembic.
revision: str = '06f9eddb32e9'
down_revision: Union[str, None] = 'e8159734f6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

especialidad_table = table(
    'especialidad',
    column('id', Integer),
    column('nombre', String),
    column('descripcion', String),
    column('is_deleted', Boolean)
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        especialidad_table,
        [
            {'nombre': 'Cardiología',
             'descripcion': 'Especialidad médica que se ocupa del estudio, diagnóstico y tratamiento de las enfermedades del corazón y del aparato circulatorio.',
             'is_deleted': False},
            {'nombre': 'Neurología',
             'descripcion': 'Especialidad médica que se ocupa del estudio, diagnóstico y tratamiento de las enfermedades del sistema nervioso.',
             'is_deleted': False},
            {'nombre': 'Pediatría',
             'descripcion': 'Especialidad médica que se ocupa del estudio, diagnóstico y tratamiento de las enfermedades de los niños.',
             'is_deleted': False},
            {'nombre': 'Dermatología',
             'descripcion': 'Especialidad médica que se ocupa del estudio, diagnóstico y tratamiento de las enfermedades de la piel.',
             'is_deleted': False},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM especialidad WHERE nombre IN ('Cardiología', 'Neurología', 'Pediatría', 'Dermatología')")
    # ### end Alembic commands ###
