"""Relations

Revision ID: 10bd1ea58f68
Revises: 0810fe6b5b98
Create Date: 2025-03-02 00:49:53.563727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bd1ea58f68'
down_revision: Union[str, None] = '0810fe6b5b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_especialidad',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidad.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'especialidad_id')
    )
    op.add_column('cita', sa.Column('paciente_id', sa.Integer(), nullable=False))
    op.add_column('cita', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cita', 'paciente', ['paciente_id'], ['id'])
    op.create_foreign_key(None, 'cita', 'doctor', ['doctor_id'], ['id'])
    op.drop_column('doctor', 'especialidad')
    op.add_column('historial_medico', sa.Column('paciente_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'historial_medico', 'paciente', ['paciente_id'], ['id'])
    op.add_column('paciente', sa.Column('seguro_medico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paciente', 'seguro_medico', ['seguro_medico_id'], ['id'])
    op.add_column('tratamiento', sa.Column('historial_medico_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tratamiento', 'historial_medico', ['historial_medico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tratamiento', type_='foreignkey')
    op.drop_column('tratamiento', 'historial_medico_id')
    op.drop_constraint(None, 'paciente', type_='foreignkey')
    op.drop_column('paciente', 'seguro_medico_id')
    op.drop_constraint(None, 'historial_medico', type_='foreignkey')
    op.drop_column('historial_medico', 'paciente_id')
    op.add_column('doctor', sa.Column('especialidad', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cita', type_='foreignkey')
    op.drop_constraint(None, 'cita', type_='foreignkey')
    op.drop_column('cita', 'doctor_id')
    op.drop_column('cita', 'paciente_id')
    op.drop_table('doctor_especialidad')
    # ### end Alembic commands ###
