"""fix: model doctor_especialidad

Revision ID: 16ba1bcd6de1
Revises: 06f9eddb32e9
Create Date: 2025-03-05 00:47:22.668910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ba1bcd6de1'
down_revision: Union[str, None] = '06f9eddb32e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_especialidad', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('doctor_especialidad', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('doctor_especialidad', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('doctor_especialidad', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_especialidad', 'deleted_at')
    op.drop_column('doctor_especialidad', 'is_deleted')
    op.drop_column('doctor_especialidad', 'updated_at')
    op.drop_column('doctor_especialidad', 'created_at')
    # ### end Alembic commands ###
